import type { NextApiResponse, NextPage } from "next";
import { AppProps } from "next/app";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../styles/Home.module.css";

const defaultEndpoint = "https://anapioficeandfire.com/api/books";

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { id } = query;
  const res = await fetch(`${defaultEndpoint}/${id}`);
  console.log("res: ", res);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

const Book: NextPage = ({ data }: AppProps) => {
  const { characters } = data;
  console.log("data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title> {data.name} </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> {data.name} </h1>

        <p> isbn: {data.isbn} </p>
        <p> authors: {data.authors} </p>
        <p> country: {data.country} </p>
        <p> released: {data.released} </p>

        <h4>Characters: </h4>
        <ul className={styles.grid}>
          {characters.map((character: string, id: number) => {
            var characterNumber = character.match(/\d+$/);
            return (
              <li key={id} Style="list-style: none">
                <Link href={`/character/${characterNumber}`}>
                  <a>
                    <h2>- {character}</h2>
                  </a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
};

export default Book;
