import type { NextApiResponse, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const defaultEndpoint = "https://anapioficeandfire.com/api/books?pageSize=15";
const charactersEndpoint = "https://anapioficeandfire.com/api/characters?pageSize=100&page=";



export const getServerSideProps: GetServerSideProps = async () => {

  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

const Home: NextPage = ({ data }: AppProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Game Of Thrones Wiki</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Books Of Ice And Fire</h1>

        <p className={styles.description}>A Game Of Thrones Wiki</p>

        <ul className={styles.grid}>
          {data.map((book: { name: string; isbn: string }, id: number) => {
            return (
              <li key={book.isbn} className={styles.card}>
                <Link href={`/book/${id + 1}`}>
                  <a>
                    <h2> {book.name} </h2>
                  </a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
