import type { NextApiResponse, NextPage } from "next";
import { AppProps } from "next/app";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { title } from "process";
import styles from "../../../styles/Home.module.css";

const defaultEndpoint = "https://anapioficeandfire.com/api/";

export const getServerSideProps: GetServerSideProps = async ({query}) => {
  const {id}  = query
  const res = await fetch(`${defaultEndpoint}/characters/${id}`);
  const data = await res.json();
  return {
    props: {
      data, 
    },
  };
};

const Home: NextPage = ({ data }: AppProps) => {  
    console.log('data:', data)
  return (
    <div className={styles.container}>
      <Head>
        <title> {data.name} </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> {data.name} </h1>

        <p> gender: {data.gender} </p>
        <p> titles:  
            {data.titles && data.titles.map((title: string, id: number)=> <p key={id} > {title} </p> )}
            {data.title} </p>

        <p>aliases: 
            {data.aliases && data.aliases.map((alias: string, id:number)=> <p key={id} >{alias}</p> ) }
        </p>

        {/* <ul className={styles.grid}>
          {data.map((book: { name: string; isbn: string }, id: number) => {
            return (
              <li key={book.isbn} className={styles.card}>
                <Link href={`/book/${book.name}`}>
                <a>
                  <h2> {book.name} </h2>
                </a>
                </Link>
              </li>
            );
          })}
        </ul> */}
      </main>

      
    </div>
  );
};

export default Home;
